# name: TF_CALLER
# on:
#   workflow_dispatch:
#     # TODO path to the data product for which we wish to launch the pipeline, if all projects stay in the 
#     # same repository
#     inputs:
      

# # Uncomment to automatically create workflow on each push
# # on:
# #   push:
# #     branches:
# #       - master
# #       - feature/*

# jobs:
#   terraform:
#     strategy:
#       matrix:
#         environment: [poc, dev]
#     uses: ./.github/workflows/shared.yaml
#     with:
#       environment: ${{ matrix.environment }}