name: TF_POC
on:
  push:
    branches:
      - master
      - feature/reusable-workflow
jobs:
  call-workflow-terraform:
    strategy:
      matrix:
        target:
          - gh-env: myenv
            config-path: poc
          - gh-env: myenv
            config-path: dev
    uses: ./.github/workflows/shared.yaml
    with:
      config-path: ${{ matrix.target.config-path }}
      gh-env:  ${{ matrix.target.gh-env }}