name: TF_CALLER
on:
  push:
    branches:
      - master
      - feature/reusable-workflow
      - feature/reusable-workflow-matrix
jobs:
  terraform:
    strategy:
      matrix:
        environment: [poc, dev]
    uses: ./.github/workflows/shared.yaml
    with:
      environment: ${{ matrix.environment }}