name: TF_CALLER
# on:
#   workflow_dispatch:
#     # TODO path to the data product for which we wish to launch the pipeline
#     inputs:
#       # dummy:
#       #   description: 'Seems inputs are mandatory'
#       #   type: string
      

# Uncomment to automatically create workflow on each push
on:
  push:
    branches:
      - master
      - feature/*
jobs:
  plan_dev:
    uses: ./.github/workflows/plan.yaml
    with:
      environment: dev
  apply_dev:
    uses: ./.github/workflows/apply.yaml
    needs: plan_dev
    with:
      environment: dev
  plan_poc:
    uses: ./.github/workflows/plan.yaml
    with:
      environment: poc
  apply_poc:
    uses: ./.github/workflows/apply.yaml
    needs: plan_poc
    with:
      environment: poc