name: NON_PROD

on:
  push:
    branches:
      - feature/*

jobs:
  plan_poc:
    uses: ./.github/workflows/plan.yaml
    with:
      environment: poc
  plan_dev:
    uses: ./.github/workflows/plan.yaml
    with:
      environment: dev
  plan_int:
    uses: ./.github/workflows/plan.yaml
    with:
      environment: int
  plan_prp:
    uses: ./.github/workflows/plan.yaml
    with:
      environment: prp
  apply_poc:
    uses: ./.github/workflows/apply.yaml
    needs: plan_poc
    with:
      environment: poc
  apply_dev:
    uses: ./.github/workflows/apply.yaml
    needs: plan_dev
    with:
      environment: dev
  apply_int:
    uses: ./.github/workflows/apply.yaml
    needs: plan_int
    with:
      environment: int
  apply_prp:
    uses: ./.github/workflows/apply.yaml
    needs: plan_prp
    with:
      environment: prp