name: TF_POC
on:
  push:
    branches:
      - master
      - feature/reusable-workflow
jobs:
  call-workflow-terraform:
    uses: ./.github/workflows/plan.yaml
    with:
      config-path: poc
      gh-env: myenv