name: PRD

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
    types:
      - ready_for_review

jobs:
  plan_prd:
    uses: ./.github/workflows/plan.yaml
    with:
      environment: prd
  apply_prd:
    uses: ./.github/workflows/apply.yaml
    needs: plan_prd
    with:
      environment: prd