name: TF_EXECUTION

on:
  workflow_dispatch:
    # TODO path to the data product for which we wish to launch the pipeline, if all projects stay in the 
    # same repository
    inputs:

# Uncomment to automatically create workflow on each push
on:
  push:
    branches:
      - master
      - feature/*

# on:
#   workflow_call:
#     inputs:
#       environment:
#         description: |
#           Environment: relative path to the folder containing the tfvars file and
#           backend config file, and GH environment in the repository
#         required: true
#         type: string

env:
  # TGENV_AUTO_INSTALL: true
  # TFENV_AUTO_INSTALL: true
  # TF_GH_USER: ${{ secrets.TF_GH_USER }}
  # TF_GH_PAT: ${{ secrets.TF_GH_PAT }}

jobs:
  TF_PLAN:
    name: TF_PLAN | GENERATE TFPLAN FILE, VALIDATE & SAVE
    strategy:
      matrix:
        environment: [poc, dev]
    # Run on Self-Runner developed and hosted by LV_NEO
    runs-on: self-hosted

    # this is needed since we are running terraform with read-only permissions
    env:
      ARM_SKIP_PROVIDER_REGISTRATION: true
    outputs:
      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}

    steps:

      # Checkout
      - name: Checkout the repository from remote to local
        uses: actions/checkout@v4

      - name: tf init
        run: terraform init -reconfigure -backend-config=${{ inputs.environment }}/config.gcs.tfbackend
      
      - name: 'Test: check wd content'
        run: ls -la

      # TODO Log in GCP once from the pod in the GKE cluster
      # - name: Log in to GCP
      #   uses:
      #   with:
      #     creds: '${{ secrets.TF_AZ_CREDS_PRJ }}'

      # Generates an execution plan for Terraform
      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
      - name: Terraform Plan
        id: tf-plan
        run: |
          export exitcode=0
          terraform plan --var-file=./${{ inputs.environment }}/terraform.tfvars -detailed-exitcode -out ${{ inputs.environment }}/tfplan || export exitcode=$?

          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT

          echo "Exit code: $exitcode"

          if [ $exitcode -eq 1 ]; then
            echo Terraform Plan Failed!
            exit 1
          else
            exit 0
          fi

      # Save plan to artifacts
      - name: Upload Terraform Plan file (tfplan) to gh artifacts store
        uses: actions/upload-artifact@v3/node20
        with:
          name: ${{ inputs.environment }}-tfplan
          path: ${{ inputs.environment }}/tfplan


  TF_APPLY:
    name: 'TF_APPLY | APPLY SAVED TFPLAN'
    strategy:
      matrix:
        environment: [poc, dev]
    needs: TF_PLAN
    environment: ${{ inputs.environment }} # Protection rules on the environment are applied to the job (like requesting a review before launching the job)
    runs-on: self-hosted

    steps:

      # Checkout
      - name: Checkout the repository from remote to local
        uses: actions/checkout@v4

      - name: tf init
        run: terraform init -reconfigure -backend-config=${{ inputs.environment }}/config.gcs.tfbackend

      - name: 'Test: check wd content'
        run: ls -la

      - uses: actions/download-artifact@v3/node20
        with:
          name: ${{ inputs.environment }}-tfplan
      
      - name: 'Test: check file presence after download'
        run: ls -la

      - name: 'Test: read tfplan exit code'
        env:
          OUTPUT1: ${{needs.TF_PLAN.outputs.tfplanExitCode}}
        run: echo "$OUTPUT1"

      - name: 'Test: run apply with the downloaded tfplan'
        run: terraform apply -auto-approve tfplan

      # TODO: log in GCP
      # - name: Log in GCP
      #   uses:
      #   with:
      #     creds: '${{ secrets.TF_AZ_CREDS_PRJ }}'
